// src/components/large-gallery.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { GalleryRow, GalleryRowConfig } from '../utils/gallery-row';
  import Animatable from './animatable.svelte';

  export let rows: GalleryRow[],
    description: string,
    botSpacing = true;

  let width: number;
  let rowFactors = rows.map((row) =>
    row.images.map((curr) => curr.width / curr.height).reduce((prev, curr) => prev + curr)
  );
  let index = 0;

  onMount(() => {
    setInterval(() => {
      index += 1;
    }, 1500);
  });
</script>

<div
  class="space-y-spacing"
  bind:clientWidth={width}
  class:mb-spacing-3lg={botSpacing}
  class:mb-spacing={!botSpacing}
>
  {#each rows as row, i}
    {#if row.config === GalleryRowConfig.FixedHeight}
      <div class="flex flex-row space-x-8">
        {#each row.images as image}
          {#if row.images.length === 1}
            <Animatable source={image} alt={`${description} gallery image`} frame={index} />
          {:else}
            <Animatable
              source={image}
              alt={`${description} gallery image`}
              frame={index}
              adaptiveHeight={true}
              totalWidth={width}
              rowCount={row.images.length}
              rowFactor={rowFactors[i]}
            />
          {/if}
        {/each}
      </div>
    {:else}
      <div
        class="grid auto-cols-fr grid-flow-col items-end gap-8"
        class:items-start={row.config === GalleryRowConfig.EqualWidthStart}
        class:items-end={row.config === GalleryRowConfig.EqualWidthEnd}
      >
        {#each row.images as image}
          <Animatable source={image} alt={`${description} gallery image`} frame={index} />
        {/each}
      </div>
    {/if}
  {/each}
</div>

// components/large-gallery.tsx
import Animatable from "./animatable";
import classNames from "classnames";
import React, { useRef, useState } from "react";
import { useElementSize, useInterval } from "usehooks-ts";

import { GalleryRow, GalleryRowConfig } from "../utils/gallery-row";

interface LargeGalleryProps {
  rows: GalleryRow[];
  description: string;
  botSpacing?: boolean;
}

const defaultProps = {
  botSpacing: true,
};

const LargeGallery: React.FC<LargeGalleryProps> = (propsIn) => {
  const props = { ...defaultProps, ...propsIn };
  const [containerRef, { width }] = useElementSize();
  const [currentFrame, setCurrentFrame] = useState(0);
  useInterval(() => {
    setCurrentFrame((orig) => orig + 1);
  }, 1500);
  let rowFactors = props.rows.map((row) =>
    row.images
      .map((curr) => curr.width / curr.height)
      .reduce((prev, curr) => prev + curr),
  );

  return (
    <div
      className={classNames("space-y-spacing w-full", {
        "mb-spacing-3lg": props.botSpacing,
        "mb-spacing": !props.botSpacing,
      })}
      ref={containerRef}
    >
      {props.rows.map((row, index) => {
        if (row.config === GalleryRowConfig.FixedHeight) {
          return (
            <div className="flex flex-row space-x-8" key={index}>
              {row.images.map((image, innerIndex) => {
                if (row.images.length === 1) {
                  return (
                    <Animatable
                      source={image}
                      alt={`${props.description} gallery image`}
                      frame={currentFrame}
                      key={innerIndex}
                    />
                  );
                } else {
                  return (
                    <Animatable
                      source={image}
                      alt={`${props.description} gallery image`}
                      frame={currentFrame}
                      adaptiveHeight={true}
                      totalWidth={width}
                      rowCount={row.images.length}
                      rowFactor={rowFactors[index]}
                      key={innerIndex}
                    />
                  );
                }
              })}
            </div>
          );
        } else {
          return (
            <div
              className={classNames("grid auto-cols-fr grid-flow-col gap-8", {
                "items-start": row.config === GalleryRowConfig.EqualWidthStart,
                "items-end": row.config === GalleryRowConfig.EqualWidthEnd,
              })}
              key={index}
            >
              {row.images.map((image, innerIndex) => (
                <Animatable
                  source={image}
                  alt={`${props.description} gallery image`}
                  frame={currentFrame}
                  key={innerIndex}
                />
              ))}
            </div>
          );
        }
      })}
    </div>
  );
};

export default LargeGallery;
