// components/top-display.tsx
import classNames from "classnames";
import Image from "next/image";
import Link from "next/link";
import React, { forwardRef } from "react";

import styles from "../styles/TopDisplay.module.css";
import { ProjectData, projectData } from "../utils/project-data";

export interface TopDisplayProps {
  project: ProjectData;
  animation: boolean;
  absolute?: boolean;
  link?: boolean;
}

const TopDisplay = forwardRef<HTMLDivElement, TopDisplayProps>((props, ref) => {
  return (
    <div
      className={classNames(
        "mb-spacing-2lg flex h-screen min-h-[30rem] flex-col xl:min-h-[34rem] w-full",
        {
          [props.project.bgColor]: true,
          "absolute top-0 left-0": props.absolute,
        },
      )}
      ref={ref}
    >
      <div className="relative min-h-0 w-full flex-shrink flex-grow overflow-hidden">
        <Image
          src={props.project.displayImage}
          alt={props.project.name}
          fill
          className="object-center object-cover"
        />
        <div className="absolute left-0 top-0 flex h-full w-full justify-center">
          <div
            className={`single mt-12 xl:mt-24 text-3xl ${props.project.titleColor}`}
          >
            {props.project.name}
          </div>
          {props.link &&
            (props.project.link.startsWith("https") ? (
              <a
                className="absolute w-full h-full top-0 left-0 block"
                href={props.project.link}
                target="_blank"
                rel="noreferrer"
              ></a>
            ) : (
              <Link
                href={props.project.link}
                className="absolute w-full h-full top-0 left-0 block"
              ></Link>
            ))}
        </div>
      </div>
      <div className="flex flex-col items-center">
        <div className="single mx-spacing-lg flex flex-row space-x-spacing py-8">
          <div className="half flex flex-col space-y-1 relative">
            <div className={`${styles.section} opacity-0`}>
              <span className={styles.heading}>Duration: </span>
              {projectData.reduce(
                (prev, curr) =>
                  prev.length > curr.duration.length ? prev : curr.duration,
                "",
              )}
            </div>
            <div className={`${styles.section} opacity-0`}>
              <span className={styles.heading}>Category: </span>
              {projectData.reduce(
                (prev, curr) =>
                  prev.length > curr.category.length ? prev : curr.category,
                "",
              )}
            </div>
            <div className={`${styles.section} opacity-0`}>
              <span className={styles.heading}>Project Focus: </span>
              {projectData.reduce(
                (prev, curr) =>
                  prev.length > curr.focus.length ? prev : curr.focus,
                "",
              )}
            </div>
            <div className="absolute left-0 top-0 w-full h-full !mt-0 flex flex-col justify-start space-y-1">
              <div className={styles.section}>
                <span className={styles.heading}>Duration: </span>
                {props.project.duration}
              </div>
              <div className={styles.section}>
                <span className={styles.heading}>Category: </span>
                {props.project.category}
              </div>
              <div className={styles.section}>
                <span className={styles.heading}>Project Focus: </span>
                {props.project.focus}
              </div>
            </div>
          </div>
          <div className="half flex flex-col justify-center relative">
            <div className={`${styles.section} opacity-0`}>
              <span className={styles.heading}>Project Brief: </span>
              {projectData.reduce(
                (prev, curr) =>
                  prev.length > curr.brief.length ? prev : curr.brief,
                "",
              )}
            </div>
            <div className="half flex flex-col absolute left-0 top-0 w-full h-full justify-start">
              <div className={styles.section}>
                <span className={styles.heading}>Project Brief: </span>
                {props.project.brief}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
});

TopDisplay.displayName = "Top Display";

export default TopDisplay;

// src/components/top-display.svelte
<script lang="ts">
  import type ProjectDescription from '../utils/project-description';

  export let image: string, description: ProjectDescription, titleColor: string;
</script>

<div class="mb-spacing-3lg flex h-screen min-h-[30rem] flex-col xl:min-h-[34rem]">
  <div class="relative min-h-0 w-full flex-shrink flex-grow">
    <img src={image} alt={description.name} class="h-full w-full object-cover" loading="lazy" />
    <div class="absolute left-0 top-0 flex h-full w-full justify-center">
      <div class={`single mt-12 xl:mt-24 text-3xl ${titleColor}`}>{description.name}</div>
    </div>
  </div>
  <div class="flex flex-col items-center">
    <div class="single mx-spacing-lg flex flex-row space-x-spacing py-8">
      <div class="half flex flex-col justify-around space-y-1">
        <div class="section">
          <span class="heading">Duration:</span>
          {description.duration}
        </div>
        <div class="section">
          <span class="heading">Category:</span>
          {description.category}
        </div>
        <div class="section">
          <span class="heading">Project Focus:</span>
          {description.focus}
        </div>
      </div>
      <div class="half flex flex-col justify-around space-y-1">
        <div class="section">
          <span class="heading">Project Brief:</span>
          {description.brief}
        </div>
      </div>
    </div>
  </div>
</div>

<style lang="postcss">
  .section {
    @apply font-extralight;
    & span {
      @apply font-semibold;
    }
  }
</style>
